services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: construction_hazard_detection
      MYSQL_USER: user
      MYSQL_PASSWORD: passcode
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  model-server:
    build: .
    command: gunicorn -w 1 -b 0.0.0.0:8000 "examples.YOLOv8_server_api.app:app"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  stream-web:
    build: .
    command: gunicorn -w 1 -b 0.0.0.0:8001 "examples.streaming_web.app:app"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  main-application:
    build: .
    command: /bin/bash -c "python src/model_fetcher.py && python main.py --config /app/config/configuration.yaml"
    volumes:
      - .:/app
      - ./config/configuration.yaml:/app/config/configuration.yaml
    depends_on:
      db:
        condition: service_healthy
      model-server:
        condition: service_started
      stream-web:
        condition: service_started
      redis:
        condition: service_started

volumes:
  db_data:
